module Asterisk
  class ConfigGenerator
    CONFIG_PATH = ENV.fetch("ASTERISK_CONFIG_PATH", Rails.root.join("asterisk/conf").to_s)

    def generate_all
      generate_pjsip
      generate_queues
      generate_extensions
    end

    def generate_pjsip
      content = pjsip_header

      Agent.find_each do |agent|
        ext = agent.sip_account.delete_prefix("SIP/").delete_prefix("PJSIP/")
        content += pjsip_endpoint(ext)
      end

      write_config("pjsip_agents.conf", content)
    end

    def generate_queues
      content = queues_header

      QueueConfig.includes(queue_memberships: :agent).find_each do |queue|
        content += queue_section(queue)
      end

      write_config("queues_dynamic.conf", content)
    end

    def generate_extensions
      content = extensions_header

      RouteRule.includes(:queue_config).ordered.each do |rule|
        content += route_extension(rule)
      end

      content += extensions_default_route

      write_config("extensions_routes.conf", content)
    end

    private

    def pjsip_header
      <<~CONF
        ; Auto-generated by Pulsar — do not edit manually
        ; Generated at: #{Time.current}

      CONF
    end

    def pjsip_endpoint(ext)
      <<~CONF
        [#{ext}](agent-template)
        auth=#{ext}-auth
        aors=#{ext}

        [#{ext}-webrtc](agent-webrtc-template)
        auth=#{ext}-auth
        aors=#{ext}

        [#{ext}-auth](agent-template-auth)
        username=#{ext}
        password=changeme#{ext}

        [#{ext}](agent-template-aor)

      CONF
    end

    def queues_header
      <<~CONF
        ; Auto-generated by Pulsar — do not edit manually
        ; Generated at: #{Time.current}

        [general]
        persistentmembers=yes
        autofill=yes
        monitor-type=MixMonitor

      CONF
    end

    def queue_section(queue)
      queue_name = queue.name.downcase.gsub(/\s+/, "_")
      members = queue.queue_memberships.order(:priority).map do |m|
        ext = m.agent.sip_account.delete_prefix("SIP/").delete_prefix("PJSIP/")
        "member => PJSIP/#{ext},#{m.priority}"
      end

      <<~CONF
        [#{queue_name}]
        musicclass=default
        strategy=#{queue.strategy}
        timeout=#{queue.timeout}
        retry=5
        wrapuptime=5
        maxlen=0
        joinempty=yes
        leavewhenempty=no
        ringinuse=no
        #{members.join("\n")}

      CONF
    end

    def extensions_header
      <<~CONF
        ; Auto-generated by Pulsar — do not edit manually
        ; Generated at: #{Time.current}

        [from-trunk]
      CONF
    end

    def route_extension(rule)
      queue_name = rule.queue_config.name.downcase.gsub(/\s+/, "_")
      pattern = rule.pattern.gsub("*", ".")
      timeout = rule.queue_config.max_wait_time
      timeout_handling = timeout_action_dialplan(rule.queue_config)

      <<~CONF
        ; #{rule.name}
        exten => _#{pattern},1,NoOp(#{rule.name}: ${EXTEN})
         same => n,Answer()
         same => n,MixMonitor(/var/spool/asterisk/recording/${UNIQUEID}.wav)
         same => n,Queue(#{queue_name},t,,,#{timeout})
        #{timeout_handling} same => n,Hangup()

      CONF
    end

    def extensions_default_route
      <<~CONF
        ; Default catch-all
        exten => _+.,1,NoOp(Default route: ${EXTEN})
         same => n,Answer()
         same => n,MixMonitor(/var/spool/asterisk/recording/${UNIQUEID}.wav)
         same => n,Queue(support,t,,,300)
         same => n,Hangup()

        exten => _X.,1,NoOp(Default route: ${EXTEN})
         same => n,Answer()
         same => n,MixMonitor(/var/spool/asterisk/recording/${UNIQUEID}.wav)
         same => n,Queue(support,t,,,300)
         same => n,Hangup()
      CONF
    end

    def timeout_action_dialplan(queue_config)
      case queue_config.timeout_action
      when "voicemail"
        " same => n,Playback(vm-goodbye)\n"
      when "redirect"
        " same => n,Queue(support,t,,,300)\n"
      else
        ""
      end
    end

    def write_config(filename, content)
      path = File.join(CONFIG_PATH, filename)
      File.write(path, content)
      Rails.logger.info("Generated Asterisk config: #{path}")
      path
    end
  end
end
