; ===========================================
; Pulsar Queue Configuration
; ===========================================

[general]
persistentmembers=yes
autofill=yes
monitor-type=MixMonitor

[support]
musicclass=default
strategy=ringall
timeout=30
retry=5
wrapuptime=5
maxlen=0
joinempty=yes
leavewhenempty=no
ringinuse=no

member => PJSIP/1001
member => PJSIP/1002
member => PJSIP/1003

[sales]
musicclass=default
strategy=leastrecent
timeout=25
retry=5
wrapuptime=5
maxlen=0
joinempty=yes
leavewhenempty=no
ringinuse=no
