; ===========================================
; Pulsar RTP Configuration
; ===========================================

[general]
rtpstart=10000
rtpend=10100
strictrtp=yes
icesupport=yes
stunaddr=stun.l.google.com:19302
