require "test_helper"

class Asterisk::ConfigGeneratorTest < ActiveSupport::TestCase
  setup do
    @generator = Asterisk::ConfigGenerator.new
    @output_dir = Dir.mktmpdir
    Asterisk::ConfigGenerator.send(:remove_const, :CONFIG_PATH) if Asterisk::ConfigGenerator.const_defined?(:CONFIG_PATH, false)
    Asterisk::ConfigGenerator.const_set(:CONFIG_PATH, @output_dir)
  end

  teardown do
    FileUtils.rm_rf(@output_dir)
  end

  test "generate_pjsip creates config file with agent endpoints" do
    @generator.generate_pjsip

    content = File.read(File.join(@output_dir, "pjsip_agents.conf"))
    assert_includes content, "Auto-generated by Pulsar"

    Agent.find_each do |agent|
      ext = agent.sip_account.delete_prefix("SIP/").delete_prefix("PJSIP/")
      assert_includes content, "[#{ext}](agent-template)"
      assert_includes content, "[#{ext}-auth](agent-template-auth)"
    end
  end

  test "generate_queues creates config with queue sections" do
    @generator.generate_queues

    content = File.read(File.join(@output_dir, "queues_dynamic.conf"))
    assert_includes content, "[general]"
    assert_includes content, "monitor-type=MixMonitor"

    QueueConfig.find_each do |q|
      queue_name = q.name.downcase.gsub(/\s+/, "_")
      assert_includes content, "[#{queue_name}]"
      assert_includes content, "strategy=#{q.strategy}"
    end
  end

  test "generate_extensions creates dialplan with route rules" do
    @generator.generate_extensions

    content = File.read(File.join(@output_dir, "extensions_routes.conf"))
    assert_includes content, "[from-trunk]"
    assert_includes content, "MixMonitor"

    RouteRule.find_each do |rule|
      assert_includes content, rule.name
    end
  end

  test "generate_extensions includes recording path" do
    @generator.generate_extensions

    content = File.read(File.join(@output_dir, "extensions_routes.conf"))
    assert_includes content, "/var/spool/asterisk/recording/${UNIQUEID}.wav"
  end
end
